//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Presenter {

    private weak var view: ___VARIABLE_moduleName___Presenter?
    private let wireframe: ___VARIABLE_moduleName___Wireframe

    init(wireframe: ___VARIABLE_moduleName___Wireframe, view: ___VARIABLE_moduleName___Presenter) {
        self.wireframe = wireframe
        self.view = view
    }

}