//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import UIKit
import Swace

final class ___VARIABLE_moduleName___Wireframe: BaseWireframe {

    override func prepare(_ data: [String : Any] = [:]) throws -> UIViewController {
        let view = ___VARIABLE_moduleName___ViewController() 
        let presenter = ___VARIABLE_moduleName___Presenter(wireframe: self, view: view)
        view.presenter = presenter
        return view
    }

    override func present(_ data: [String : Any] = [:], from source: BaseWireframe?) throws {
        let view = try prepare()
        // The views has been prepared. This is a good place to wire up any transition delegates etc. 
    }
    
    override func dismiss(_ view: UIViewController?) {
        // Perform any actions needed before dismissing the view here
    }

}