//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import UIKit

class ___VARIABLE_moduleName___ViewController: UIViewController {

    var presenter: ___VARIABLE_moduleName___Presenter!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}