//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import Foundation

protocol ___VARIABLE_moduleName___InteractorInput: class {

}

protocol ___VARIABLE_moduleName___InteractorOutput: class {
    
}

final class ___VARIABLE_moduleName___Interactor {
    weak var presenter: ___VARIABLE_moduleName___InteractorOutput?
    var dataManager: ___VARIABLE_moduleName___DataManager!
}

//MARK: - Extensions

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorInput {
    
}

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___DataManagerOutput {
    
}