//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import Foundation

protocol ___VARIABLE_moduleName___DataManagerInput: class {

}

protocol ___VARIABLE_moduleName___DataManagerOutput: class {
    
}

final class ___VARIABLE_moduleName___DataManager {
    private var service: ___VARIABLE_moduleName___Service = ___VARIABLE_moduleName___Service()
    weak var interactor: ___VARIABLE_moduleName___DataManagerOutput?
}

//MARK: - Extensions

extension ___VARIABLE_moduleName___DataManager: ___VARIABLE_moduleName___DataManagerInput {
    
}