//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by @oshtman's VIPER generator
//

import Foundation

protocol ___VARIABLE_moduleName___ServiceInput: class {

}

protocol ___VARIABLE_moduleName___ServiceOutput: class {
    
}

final class ___VARIABLE_moduleName___Service {

}

//MARK: - Extensions

extension ___VARIABLE_moduleName___Service: ___VARIABLE_moduleName___ServiceInput {
    
}